refactor: добавить возможность рейтинга фильмов и добавления в друзья
AndreyReset/java-filmorate pull request #3
Opened 2022-05-30 19:14 UTC by AndreyReset

2022-05-30 19:18 UTC, AndreyReset commented
На компьютере в постмане все тесты проходит, тут не запускается, вроде пишут проблема на стороне гитхаба

2022-05-31 04:45 UTC, eugene-lenkevich requested changes
Привет,  Андрей, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

И проверь, пожалуйста, проходят ли автоматические тесты, вроде красненькие

2022-05-31 04:45 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmController(FilmStorage filmStorage, FilmService filmService) {
FilmStorage filmStorage же не используется далее :)

А еще можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

2022-05-31 04:45 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public Film create(Film film, HttpServletResponse response) {
У нас есть три слоя данных:
- уровень web, конроллер
- уровень бизнес логики, сервис
- уровень базы данных

в данном случае на уровень бизнес-логики передается кусочек, относящийся к вэб, это не очень хорошо, все таки каждый должен заниматься только своими вещами. Сервис может дергаться и в других местах, где нет никакого HttpResponse. Обработку кодов ответов стоит перенести в контроллер, в сервисе только проверки с точки зрения бизнес-логики безотносительно контекста вызова :)

2022-05-31 04:45 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/valid/CustomException.java
> +public class CustomException extends RuntimeException {
А необходимо ли тут непроверяемое исключение?
Пользователь ввел некорректные данные, какая то сущность не найдена и тп - вполне себе штатные ситуации, пусть тут будет проверяемое исключение :)
extends Exception

2022-06-01 12:13 UTC, closed without merging